### ISSUE TITLE
Bit of feedback

### ISSUE THREAD

**Issue by FlanGrande** [FakeMichau/fgmod#2]
Hi there, just a bit of feedback for your enjoyment!

Nvidia driver 560 is now out on Linux, IDK if the script still needs to point to 555 or what, but it's worth noting.
That I'm sure you were aware.

More importantly, though, the uninstall script tries to remove the mod from /usr/share/fgmod, but prepare.sh installs everything on $HOME/fgmod

**Comment by FakeMichau** [comment]
First of all, thanks for reaching out.

The script downloads the Nvidia driver just to get a signed nvngx.dll instead of hosting it which I don't think you are allowed to do. The version doesn't matter. This is needed for the game to load the mod after one of the updates to streamline. A renamed nvngx_dlss.dll can also be used but finding the correct file on the file system just seems like more work. 
I have plans to look into the possibility of using [hosted nvngx_dlss.dll](https://github.com/NVIDIA/DLSS/tree/main/lib/Windows_x86_64/rel) file by Nvidia themselves.

In relation to the uninstaller - prepare.sh [seds](https://github.com/FakeMichau/fgmod/blob/e1eaf73dd2e1103ab674a3c96bf652245e8084ee/prepare.sh#L62) the value in the uninstaller with the correct one during installation. It's done to make the AUR package easier (which needs some work btw) but also let you change the installation folder. If you look into your file in ``~/fgmod/fgmod-uninstaller.sh`` the value should be correct.

Will close it for now. If you have any more concerns then please share and I'll reopen the issue.

**Comment by FlanGrande** [comment]
Thanks that's good to know. I think I was looking at the project's uninstaller.sh, rather than the one in the fgmod folder. That makes more sense now. Thanks!
