### ISSUE TITLE
Follow XDG Base Directory Specification instead of just yeeting into /home/

### ISSUE THREAD

**Issue by BruebachL** [FakeMichau/fgmod#5]
Hi, thanks for your work on this.
It would be great if this project could follow the appropriate [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/index.html).
It's the closest thing we have to a standard on where to place files in Linux and its aim is moving folders out of the home directory (as in, the top-level directory) and into their appropriate dot-file folders (.config or .share) or even into even more relevant folders such as /usr/share (Any program or package which contains or requires data that doesn't need to be modified should store that data in /usr/share [or /usr/local/share, if installed locally]. from the [Linux Foundation Reference Specs](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html)).

Thank you :)

**Comment by BruebachL** [comment]
After a review of the script itself, I've found that there are options to not clutter the home directory.
Please consider adding these to the README.

**Comment by FakeMichau** [comment]
I did it this way so that the steam deck can use it without many issues as well as to make the path short. But you gave an idea - using ``$XDG_DATA_HOME`` when possible and putting the script itself in ``$HOME/.local/bin`` if it's in ``$PATH``.
Definitely worth looking into. Will reopen it for now as I investigate.
